sudo: required
services:
    - docker
env:
    global:
        - SHA=$(git rev-parse HEAD)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
    - openssl aes-256-cbc -K $encrypted_9265e0f04cfc_key -iv $encrypted_9265e0f04cfc_iv -in do_not_commit_service_account.json.enc -out do_not_commit_service_account.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file service-account.json
    - gcloud config set project multi-k8s-278306
    - gcloud config set compute/zone us-central1-a
    - gcloud container clusters get-credentials multi-k8s-cluster
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t gorbar/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true gorbar/react-test npm run test -- --coverage

deploy:
    provider: script
    script: bash ./deploy.sh
    on:
        branch: master